### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc-archive/nanoc-git#1]

**Comment by lifepillar** [comment]
@ddfreyne I've (finally!) tagged a 1.0.0 release, but I don't have permissions to publish it on Rubygems.

**Comment by denisdefreyne** [comment]
There apparently already is a [nanoc-git gem on Rubygems](https://rubygems.org/gems/nanoc-git), owned by @cspicker (although not updated in ±4 years).

@cspicker Would you be willing to add push permissions for nanoc-git to both of us?

**Comment by lifepillar** [comment]
This is ready to be pushed to RubyGems (the current release is 1.0.1).

@cspickert It seems that you are not updating your nanoc-git gem any longer. Would you give us permissions to push the official nanoc-git to RubyGems?

**Comment by cspickert** [comment]
Yep, definitely. I just added you as owners of the nanoc-git gem.

**Comment by denisdefreyne** [comment]
Will release now!

**Comment by denisdefreyne** [comment]
Done. Apologies for letting this lay around for so long.

**Comment by lifepillar** [comment]
Great! Thanks you guys.
