### ISSUE TITLE
Missing instructions for requiring

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc-archive/nanoc-git#3]
Running `nanoc deploy` without explicitly requiring `nanoc-git` leads to the following error:

> The specified deploy target has an unrecognised kind “git” (expected one of fog, rsync).

The README should be updated to reflect that `nanoc-git` needs to be required first (somewhere in `lib/`).

CC @samstarling

**Comment by lifepillar** [comment]
Fixed in 248d22e9ed46059144411d4540aabc3c5dca4708.

**Comment by samstarling** [comment]
Hurrah, thanks!
